---
title: "Phase 3 Analyses"
author: "Matthew Kaufmann"
date: '`r Sys.Date()`'
output: html_document
code_folding: hide
---
```{r, echo = FALSE, include = FALSE}
# Clear environment
rm(list=ls())

# R Packages
if (!require('pacman')) install.packages('pacman'); library(pacman) 
p_load("devtools", "scales", "ellipse", "lazyeval", "igraph",  "ggraph", 
       "reshape2", "knitr", "stringr", "jsonlite", "rstudioapi", "tidyverse",
       "dampack", "data.table", "tornado", "ggplot2", "viridis",
       "kableExtra")                

```
***
```{r}
## Load model parameters
## Load model
source("02_phase3_functions.R")
source("b19_params_function.R")
l_params_all <- load_params()
v_names_str <- c("Status Quo", "Screening", "Vaccination", "Vaccination and Screening")
n_str <- length(v_names_str)



```
***

```{r}
# Run base case (non-epidemic year - 1%)
l_params_all$p_inf <- 0.01
base_case_results_nonpeak  <- parvo_model(l_params_all)

base_case_results_nonpeak$Inc.Fetal.Deaths    <- base_case_results_nonpeak[, 2] - base_case_results_nonpeak[1, 2]
base_case_results_nonpeak$Inc.Transfusions    <- base_case_results_nonpeak[, 3] - base_case_results_nonpeak[1, 3]
base_case_results_nonpeak$Inc.B19.Deaths      <- base_case_results_nonpeak[, 4] - base_case_results_nonpeak[1, 4]
base_case_results_nonpeak$Inc.B19.Stillbirths <- base_case_results_nonpeak[, 5] - base_case_results_nonpeak[1, 5]
base_case_results_nonpeak %>%
  mutate(across(2:9, \(x) round(x, 1))) %>%
  kable() %>%
  kable_styling()

# Run base case (epidemic year - 7.5%)
l_params_all$p_inf <- 0.075
base_case_results_peak  <- parvo_model(l_params_all)

base_case_results_peak$Inc.Fetal.Deaths    <- base_case_results_peak[, 2] - base_case_results_peak[1, 2]
base_case_results_peak$Inc.Transfusions    <- base_case_results_peak[, 3] - base_case_results_peak[1, 3]
base_case_results_peak$Inc.B19.Deaths      <- base_case_results_peak[, 4] - base_case_results_peak[1, 4]
base_case_results_peak$Inc.B19.Stillbirths <- base_case_results_peak[, 5] - base_case_results_peak[1, 5]
base_case_results_peak %>%
  mutate(across(2:9, \(x) round(x, 1))) %>%
  kable() %>%
  kable_styling()

``` 


```{r, warning = FALSE, message=FALSE}
### one way sensitivity analysis
# disable scientific notation
options(scipen = 999) 

# varying infection rate, and detection rate
df_params_owsa <- data.frame(pars = c("p_imm", "p_inf", "p_vax", "p_vax_eff"),
                             # min parameter values
                             min  = c(0.25, 0.01, 0.2, 0.5), 
                             # max parameter values
                             max  = c(0.75, 0.20, 0.8, 1)
                             )
# OWSA
owsa_results <- run_owsa_det(params_range = df_params_owsa,  
                             # list of all params
                             params_basecase = l_params_all, 
                             # number of param values
                             nsamp      = 100, 
                             # function to compute outputs
                             FUN        = parvo_model, 
                             # outcomes
                             outcomes = c('B19_Stillbirths', 'B19_Deaths', 'Transfusions'),
                             # names of the strategies
                             strategies = v_names_str,
                             progress = FALSE)

intercepts <- data.frame(parameter = c("Infection Rate", "Proportion Immune",
                                       "Vaccination Coverage", "Vaccine Effectiveness"),
                         xint = c(l_params_all$p_inf, l_params_all$p_imm,
                                  l_params_all$p_vax, l_params_all$p_vax_eff))

## One-way plots
# Stillbirths
owsa_results$owsa_B19_Stillbirths <- owsa_results$owsa_B19_Stillbirths %>%
  mutate(parameter = ifelse(parameter == "p_imm", "Proportion Immune",
                            ifelse(parameter == "p_inf", "Infection Rate",
                                   ifelse(parameter == "p_vax", "Vaccination Coverage",
                                          ifelse(parameter == "p_vax_eff", "Vaccine Effectiveness",
                                                 parameter))))) %>%
  mutate(strategy = ifelse(strategy == "Status.Quo", "Status Quo",
                           ifelse(strategy == "Vaccination.and.Screening", "Screening + Vaccination", 
                                  ifelse(strategy == "Screening", "Screening",
                                         ifelse(strategy == "Vaccination", "Vaccination", strategy)))))
plot(owsa_results$owsa_B19_Stillbirths) +
  ylab("Expected B19 Stillbirths") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~parameter, labeller = label_wrap_gen(30), scales = "free_x") +
  labs(colour = "Strategy") +
  theme_bw() +
  geom_vline(data = intercepts, aes(xintercept = xint), linetype = "dashed") +
  theme(legend.position = "bottom") 

ggsave(path = "Phase 3 Plots", filename = "owsa_stillbirths.png")

# B19 fetal deaths
owsa_results$owsa_B19_Deaths <- owsa_results$owsa_B19_Deaths %>%
  mutate(parameter = ifelse(parameter == "p_imm", "Proportion Immune",
                            ifelse(parameter == "p_inf", "Infection Rate",
                                   ifelse(parameter == "p_vax", "Vaccination Coverage",
                                          ifelse(parameter == "p_vax_eff", "Vaccine Effectiveness",
                                                 parameter))))) %>%
  mutate(strategy = ifelse(strategy == "Status.Quo", "Status Quo",
                           ifelse(strategy == "Vaccination.and.Screening", "Screening + Vaccination", 
                                  ifelse(strategy == "Screening", "Screening",
                                         ifelse(strategy == "Vaccination", "Vaccination", strategy)))))
plot(owsa_results$owsa_B19_Deaths) +
  ylab("Expected B19 Fetal Deaths") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~parameter, labeller = label_wrap_gen(30), scales = "free_x") +
  labs(colour = "Strategy") +
  theme_bw() +
  geom_vline(data = intercepts, aes(xintercept = xint), linetype = "dashed") +
  theme(legend.position = "bottom") 

ggsave(path = "Phase 3 Plots", filename = "owsa_b19deaths.png")

# Transfusions
owsa_results$owsa_Transfusions <- owsa_results$owsa_Transfusions %>%
  mutate(parameter = ifelse(parameter == "p_imm", "Proportion Immune",
                            ifelse(parameter == "p_inf", "Infection Rate",
                                   ifelse(parameter == "p_vax", "Vaccination Coverage",
                                          ifelse(parameter == "p_vax_eff", "Vaccine Effectiveness",
                                                 parameter))))) %>%
  mutate(strategy = ifelse(strategy == "Status.Quo", "Status Quo",
                           ifelse(strategy == "Vaccination.and.Screening", "Screening + Vaccination", 
                                  ifelse(strategy == "Screening", "Screening",
                                         ifelse(strategy == "Vaccination", "Vaccination", strategy)))))
plot(owsa_results$owsa_Transfusions) +
  ylab("Expected Fetal Transfusions") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~parameter, labeller = label_wrap_gen(30), scales = "free_x") +
  labs(colour = "Strategy") +
  theme_bw() +
  geom_vline(data = intercepts, aes(xintercept = xint), linetype = "dashed") +
  theme(legend.position = "bottom") 
ggsave(path = "Phase 3 Plots", filename = "owsa_transfusion.png")

owsa_results$owsa_B19_Stillbirths$outcome <- "B19 Stillbirths"
owsa_results$owsa_B19_Deaths$outcome      <- "B19 Fetal Deaths"
owsa_results$owsa_Transfusions$outcome    <- "Fetal Transfusions"

df_owsa_all <- rbind(owsa_results$owsa_B19_Stillbirths,
                     owsa_results$owsa_B19_Deaths,
                     owsa_results$owsa_Transfusions)
df_owsa_all$strategy <- factor(df_owsa_all$strategy,
                               levels = c("Status Quo", "Screening", "Vaccination", "Screening + Vaccination"))

equal_breaks <- function(n = 3, s = 0.05, r = 0,...){
  function(x){
    d <- s * diff(range(x)) / (1+2*s)
    seq = seq(min(x)+d, max(x)-d, length=n)
    if(seq[2]-seq[1] < 10^(-r)) seq else round(seq, r)
  }
}

ggplot(data = df_owsa_all, aes(x = param_val, y = outcome_val, color = strategy)) +
  geom_line(size = 1.2) +
  facet_grid(outcome~parameter, labeller = label_wrap_gen(18),
             scales = "free") +
  ylab("") +
  xlab("Parameter Value") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = equal_breaks(n = 4, s = 0.2)) +
  scale_color_viridis(option = "turbo", discrete = TRUE) +
  labs(colour = "Strategy") +
  theme_bw() +
  geom_vline(data = intercepts, aes(xintercept = xint), linetype = "dashed") +
  theme(legend.position = "bottom") 
ggsave(path = "Phase 3 Plots", filename = "owsa_all.png")
```


***
```{r, warning = FALSE}
# two way sensitivity analysis of immunity and infection rate

df_params_twsa <- data.frame(pars = c("p_imm", "p_inf"),
                              # min parameter values
                              min  = c(0.25, 0.01), 
                              # max parameter values
                              max  = c(0.75, 0.20) 
                              )
# twsa dataframes for immunity and infection rate
twsa_results <- run_twsa_det(params_range = df_params_twsa, 
                             # list with all parameters
                             params_basecase = l_params_all,
                             # number of parameter values
                             nsamp      = 10,               
                             # function to compute outputs
                             FUN        = parvo_model, 
                             # outcomes
                             outcomes = c('B19_Stillbirths', 'Transfusions'),
                             # names of the strategies
                             strategies = v_names_str,
                             progress = FALSE)


## heat maps status quo vs Screening
twsa_deaths    <- twsa_results$twsa_B19_Stillbirths %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Screening) %>%
  as.matrix()

heat_deaths_ii <- ggplot(data = twsa_deaths, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("B19 Stillbirths Averted: Status Quo vs. Routine Screening") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="B19 Stillbirths Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_deaths_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_deaths_sq_test.png",
       height = 7, width = 7)

twsa_transfusions <- twsa_results$twsa_Transfusions %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Screening) %>%
  as.matrix()

heat_transfusions_ii <- ggplot(data = twsa_transfusions, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("Transfusions Averted: Status Quo vs. Routine Screening") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="Transfusions Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_transfusions_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_trans_sq_test.png",
       height = 7, width = 7)

## heat maps status quo vs vaccination
twsa_deaths    <- twsa_results$twsa_B19_Stillbirths %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Vaccination) %>%
  as.matrix()

heat_deaths_ii <- ggplot(data = twsa_deaths, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("B19 Stillbirths Averted: Status Quo vs. Vaccination") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="B19 Stillbirths Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_deaths_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_deaths_sq_vax.png",
       height = 7, width = 7)

twsa_transfusions <- twsa_results$twsa_Transfusions %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Vaccination) %>%
  as.matrix()

heat_transfusions_ii <- ggplot(data = twsa_transfusions, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("Transfusions Averted: Status Quo vs. Vaccination") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="Transfusions Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_transfusions_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_trans_sq_vax.png",
       height = 7, width = 7)

## heat maps status quo vs vaccination + Screening
twsa_deaths    <- twsa_results$twsa_B19_Stillbirths %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Vaccination.and.Screening) %>%
  as.matrix()

heat_deaths_ii <- ggplot(data = twsa_deaths, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("B19 Stillbirths Averted: Status Quo vs. Vaccination + Screening") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="B19 Stillbirths Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_deaths_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_deaths_sq_testvax.png",
       height = 7, width = 7)

twsa_transfusions <- twsa_results$twsa_Transfusions %>%
  pivot_wider(names_from = strategy,
              values_from = outcome_val) %>%
  mutate(incremental = Status.Quo - Vaccination.and.Screening) %>%
  as.matrix()

heat_transfusions_ii <- ggplot(data = twsa_transfusions, mapping = aes(x = p_imm,
                                                  y = p_inf,
                                                  fill = incremental)) +
  geom_tile() +
  geom_text(aes(label = round(incremental, 0))) +
  xlab(label = 'Proportion Immune') +
  ylab(label = 'Infection Rate') +
  ggtitle("Transfusions Averted: Status Quo vs. Vaccination + Screening") +
  scale_fill_viridis(option = "turbo", alpha = 0.75) +
  guides(fill=guide_legend(title="Transfusions Averted")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(legend.position = "none")

heat_transfusions_ii
ggsave(path = "Phase 3 Plots", filename = "twsa_imm_inf_trans_sq_testvax.png",
       height = 7, width = 7)


### Optimal strategy (vaccine coverage and effectiveness)
df_params_twsa_opt <- data.frame(pars = c("p_vax", "p_vax_eff"),
                             # min parameter values
                             min  = c(0.2, 0.5), 
                             # max parameter values
                             max  = c(0.8, 1)
                             )
l_params_all <- load_params()
v_names_str <- c("Screening", "Vaccination")
n_str <- length(v_names_str)

# twsa dataframes for immunity and infection rate
twsa_results_opt <- run_twsa_det(params_range = df_params_twsa_opt, 
                                 # list with all parameters
                                 params_basecase = l_params_all,
                                 # number of parameter values
                                 nsamp      = 100,               
                                 # function to compute outputs
                                 FUN        = parvo_model_tw, 
                                 # outcomes
                                 outcomes = c('B19_Stillbirths'),
                                 # names of the strategies
                                 strategies = c("Screening", "Vaccination"),
                                 progress = FALSE)
twsa_results_opt <- twsa_results_opt %>%
  mutate(outcome_val = outcome_val * -1) %>%
  rename(`Vaccination Coverage` = p_vax) %>%
  rename(`Vaccine Effectiveness` = p_vax_eff)
# plot optimal strategy as a function of the two parameters varied in the two-way DSA
plot(twsa_results_opt) +
  scale_fill_manual(values=c("#1AE4B6FF", "#FABA39FF")) +
  theme_bw() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(fill = "Strategy") +
  geom_point(mapping = aes(x = 0.5, y = 0.9), shape = 8)

ggsave(path = "Phase 3 Plots", filename = "twsa_optimal.png",
       height = 5, width = 9)
```

```{r, warning=FALSE}
### Probabilistic Sensitivity Analysis
## Generate PSA samples
n_samp <- 10000
my_params <- names(get_params_sa())
my_psa_params <- gen_psa_samp(params = my_params,
                              dists = my_dists,
                              parameterization_types = my_parameterization_types,
                              dists_params = my_dists_params,
                              n = n_samp)

## Make modifications to PSA parameter sets
# Rank ordering
# probability of detection
m_p_det <- ordered_params(n_samp * 100,
                         c(my_dists_params[[3]][1], my_dists_params[[4]][1]),
                         c(my_dists_params[[3]][2], my_dists_params[[4]][2]),
                         tol = 0.0001)
row_indices <- which(m_p_det[,1] > m_p_det[,2])
my_psa_params[,4:5] <- m_p_det[row_indices[1:n_samp], ]
# probability of transfusion (detected vs. undetected)
m_p_it <- ordered_params(n_samp * 100,
                         c(my_dists_params[[9]][1], my_dists_params[[10]][1]),
                         c(my_dists_params[[9]][2], my_dists_params[[10]][2]),
                         tol = 0.0001)
row_indices <- which(m_p_it[,1] > m_p_it[,2])
my_psa_params[,10:11] <- m_p_it[row_indices[1:n_samp], ]
# probability of live birth after severe fetal anemia (detected vs. undetected)
m_p_sfa_lb <- ordered_params(n_samp * 100,
                         c(my_dists_params[[12]][1], my_dists_params[[13]][1]),
                         c(my_dists_params[[12]][2], my_dists_params[[13]][2]),
                         tol = 0.0001)
row_indices <- which(m_p_sfa_lb[,1] > m_p_sfa_lb[,2])
my_psa_params[,13:14] <- m_p_sfa_lb[row_indices[1:n_samp], ]
# Values that should all be the same
my_psa_params$p_det_inf <- my_psa_params$p_det_sus <- my_psa_params$p_det_surv
my_psa_params$p_det_imm <- my_psa_params$p_det_sq
my_psa_params$p_und_sfa_lb_nt <-  my_psa_params$p_det_sfa_lb_nt

# Fix probability of infection
my_psa_params$p_inf <- 0.075

my_params_basecase <- l_params_all
psa_output <- run_psa(psa_samp = my_psa_params,
                      params_basecase = my_params_basecase,
                      FUN = parvo_model,
                      outcomes = c('B19_Stillbirths', 'Transfusions'),
                      strategies = c("Status Quo", "Screening", "Vaccination", "Vaccination and Screening"),
                      progress = TRUE)

df_psa_stillbirth <- psa_output[["B19_Stillbirths"]][["other_outcome"]] %>%
  mutate(max = names(.)[max.col(.)]) %>%
  mutate(min_sb = pmin(`Status Quo`, `Screening`, `Vaccination`, `Vaccination and Screening`)) %>%
  mutate(min = ifelse(`Status Quo` == min_sb, "Status Quo",
                      ifelse(`Screening` == min_sb, "Screening",
                             ifelse(`Vaccination` == min_sb, "Vaccination", "Vaccination and Screening")))) %>%
  mutate(Screening_inc = `Screening` - `Status Quo`) %>%
  mutate(vax_inc = `Vaccination` - `Status Quo`) %>%
  mutate(vax_Screening_inc = `Vaccination and Screening` - `Status Quo`) %>%
  mutate(my_ranks = pmap(select(., c(`Status Quo`, `Screening`, `Vaccination`, `Vaccination and Screening`)), ~ 
           as_tibble_row(rank(c(...)),
            .name_repair = ~ str_c('rank', seq_along(.))))) %>%
     unnest(c(my_ranks))

c(quantile(df_psa_stillbirth$Screening_inc, 0.025), quantile(df_psa_stillbirth$Screening_inc, 0.975))
c(quantile(df_psa_stillbirth$vax_inc, 0.025), quantile(df_psa_stillbirth$vax_inc, 0.975))
c(quantile(df_psa_stillbirth$vax_Screening_inc, 0.025), quantile(df_psa_stillbirth$vax_Screening_inc, 0.975))

df_psa_trans <- psa_output[["Transfusions"]][["other_outcome"]] %>%
  mutate(my_ranks = pmap(select(., c(`Status Quo`, `Screening`, `Vaccination`, `Vaccination and Screening`)), ~ 
           as_tibble_row(rank(c(...)),
            .name_repair = ~ str_c('rank', seq_along(.))))) %>%
     unnest(c(my_ranks))
```

