---
title: "Phase 2 Base Case"
author: "Ritesh Sivakumar"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo = FALSE, include = FALSE}
# Clear environment
rm(list=ls())

# R Packages
if (!require('pacman')) install.packages('pacman'); library(pacman) 
p_load("devtools", "scales", "ellipse", "lazyeval", "igraph",  "ggraph", "reshape2", "knitr", "stringr", "jsonlite", "rstudioapi", "tidyverse", "dampack", "data.table", "tornado", "ggplot2", "viridis")                

```
***
```{r}
# probabilities
# proportion of population immune
p_imm <- 0.5
# infection rate (1% during nonepidemic years, 6.5% during epidemic years)
p_inf <- 0.01 # varied from 0.5-2% and 5-10%
# proportion of maternal infections detected
p_det_sq <- 0.05
p_det_surv <- 0.5 #varied from 0.1-0.5
# probability of fetus developing severe fetal anemia
p_sfa <- 0.075
# probability of transfusion in detected
p_det_it <- 0.95
#probability of transfusion in undetected
p_und_it <- 0.8

# probability of live birth
p_lb <- 1
# probability of live birth if mother undetected and severe fetal anemia (0.807)
p_und_sfa_lb <- (p_lb)*(0.807)
# probability of live birth if mother detected and severe fetal anemia (0.891)
p_det_sfa_lb <- (p_lb)*(0.891)
# Probability of survival if not transfused
p_det_sfa_lb_nt <- (0.01)*(p_lb)
p_und_sfa_lb_nt <- (0.01)*(p_lb)

# QALY
#qaly_lb <- 78.8
#qaly_fd <- 0

# Cost
# average cost of live birth
c_lb <- 11000
# average cost of fetal death
c_fd <- 6000
# average cost of severe fetal anemia
c_sfa <- 2000
# average cost of detecting infection in mother
c_mid <- 130
# average cost of monitoring for severe fetal anemia (400 per ultrasound, with average of 6 weeks monitoring)
c_mon <- 2400
# average cost of status quo surveillance
c_sq <- 0
# average cost of surveillance
c_surv <- 124000

# Deaths averted
# number of births
d_lb <- 0
# number of deaths
d_fd <- 1
# non pvb19 associated birth or death
d_p_lb <- 0
# pvb19 associated death
d_p_fd <- 1

# Expected number of intrauterine transfusions
# number of transfusions
n_it <- 1
# number of no transfusions
n_nt <- 0


# population parameters
pop_size <- 65000

# list of parameters
l_params_all <- list(p_imm, p_inf, p_det_sq, p_det_surv, p_sfa, p_det_it, p_und_it, p_lb, p_und_sfa_lb, p_det_sfa_lb, c_lb, c_fd, c_sfa, c_mid, c_mon, c_sq, c_surv, d_lb, d_fd, n_it, n_nt, pop_size)

v_names_params <- c('p_imm', 'p_inf', 'p_det_sq', 'p_det_surv', 'p_sfa', 'p_det_it', 'p_und_it', 'p_lb', 'p_und_sfa_lb', 'p_det_sfa_lb', 'c_lb', 'c_fd', 'c_sfa', 'c_mid', 'c_mon', 'c_sq', 'c_surv', 'd_lb', 'd_fd', 'n_it', 'n_nt', 'pop_size')

names(l_params_all) <- v_names_params

v_names_str <- c("Status Quo", "Surveillance")
n_str <- length(v_names_str) 

```
***
```{r}
# expected value calculations
run_tree <- function(l_params_all) {
  with(
    as.list(l_params_all),
    {
    # vector of weights for each policy
    # status quo vector
    v_w_sq <- c((1-p_imm)*p_inf*p_det_sq*p_sfa*p_det_it*p_det_sfa_lb,
                (1-p_imm)*p_inf*p_det_sq*p_sfa*p_det_it*(1-p_det_sfa_lb),
                (1-p_imm)*p_inf*p_det_sq*p_sfa*(1-p_det_it)*p_det_sfa_lb_nt,
                (1-p_imm)*p_inf*p_det_sq*p_sfa*(1-p_det_it)*(1-p_det_sfa_lb_nt),
                (1-p_imm)*p_inf*p_det_sq*(1-p_sfa)*p_lb,
                (1-p_imm)*p_inf*p_det_sq*(1-p_sfa)*(1-p_lb),
                (1-p_imm)*p_inf*(1-p_det_sq)*p_sfa*p_und_it*p_und_sfa_lb,
                (1-p_imm)*p_inf*(1-p_det_sq)*p_sfa*p_und_it*(1-p_und_sfa_lb),
                (1-p_imm)*p_inf*(1-p_det_sq)*p_sfa*(1-p_und_it)*p_und_sfa_lb_nt,
                (1-p_imm)*p_inf*(1-p_det_sq)*p_sfa*(1-p_und_it)*(1-p_und_sfa_lb_nt),
                (1-p_imm)*p_inf*(1-p_det_sq)*(1-p_sfa)*p_lb,
                (1-p_imm)*p_inf*(1-p_det_sq)*(1-p_sfa)*(1-p_lb),
                (1-p_imm)*(1-p_inf)*p_lb,
                (1-p_imm)*(1-p_inf)*(1-p_lb),
                p_imm*p_lb,
                p_imm*(1-p_lb))
    
    # surveillance vector
    v_w_surv <- c((1-p_imm)*p_inf*p_det_surv*p_sfa*p_det_it*p_det_sfa_lb,
                  (1-p_imm)*p_inf*p_det_surv*p_sfa*p_det_it*(1-p_det_sfa_lb),
                  (1-p_imm)*p_inf*p_det_surv*p_sfa*(1-p_det_it)*p_det_sfa_lb_nt,
                  (1-p_imm)*p_inf*p_det_surv*p_sfa*(1-p_det_it)*(1-p_det_sfa_lb_nt),
                  (1-p_imm)*p_inf*p_det_surv*(1-p_sfa)*p_lb,
                  (1-p_imm)*p_inf*p_det_surv*(1-p_sfa)*(1-p_lb),
                  (1-p_imm)*p_inf*(1-p_det_surv)*p_sfa*p_und_it*p_und_sfa_lb,
                  (1-p_imm)*p_inf*(1-p_det_surv)*p_sfa*p_und_it*(1-p_und_sfa_lb),
                  (1-p_imm)*p_inf*(1-p_det_surv)*p_sfa*(1-p_und_it)*p_und_sfa_lb_nt,
                  (1-p_imm)*p_inf*(1-p_det_surv)*p_sfa*(1-p_und_it)*(1-p_und_sfa_lb_nt),
                  (1-p_imm)*p_inf*(1-p_det_surv)*(1-p_sfa)*p_lb,
                  (1-p_imm)*p_inf*(1-p_det_surv)*(1-p_sfa)*(1-p_lb),
                  (1-p_imm)*(1-p_inf)*p_lb,
                  (1-p_imm)*(1-p_inf)*(1-p_lb),
                  p_imm*p_lb,
                  p_imm*(1-p_lb))
      
    # vector of costs for status quo
    v_cost_sq <-c(c_lb + c_sfa + c_mid + c_mon + c_sq,
                  c_fd + c_sfa + c_mid + c_mon + c_sq,
                  c_lb + c_sfa + c_mid + c_mon + c_sq,
                  c_fd + c_sfa + c_mid + c_mon + c_sq,
                  c_lb + c_mid + c_mon + c_sq,
                  c_fd + c_mid + c_mon + c_sq,
                  c_lb + c_sfa + c_mid + c_sq,
                  c_fd + c_sfa + c_mid + c_sq,
                  c_lb + c_sfa + c_mid + c_sq,
                  c_fd + c_sfa + c_mid + c_sq,
                  c_lb + c_sq,
                  c_fd + c_sq,
                  c_lb + c_sq,
                  c_fd + c_sq,
                  c_lb + c_sq,
                  c_fd + c_sq)
    
    # vector of costs for surveillance
    v_cost_surv <-c(c_lb + c_sfa + c_mid + c_mon + c_surv,
                  c_fd + c_sfa + c_mid + c_mon + c_surv,
                  c_lb + c_sfa + c_mid + c_mon + c_surv,
                  c_fd + c_sfa + c_mid + c_mon + c_surv,
                  c_lb + c_mid + c_mon + c_surv,
                  c_fd + c_mid + c_mon + c_surv,
                  c_lb + c_sfa + c_mid + c_surv,
                  c_fd + c_sfa + c_mid + c_surv,
                  c_lb + c_sfa + c_mid + c_surv,
                  c_fd + c_sfa + c_mid + c_surv,
                  c_lb + c_surv,
                  c_fd + c_surv,
                  c_lb + c_surv,
                  c_fd + c_surv,
                  c_lb + c_surv,
                  c_fd + c_surv)
    
    # vector of total deaths
    v_death <- c(d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd,
                 d_lb,
                 d_fd)
    
    # vector of parvovirus deaths
    v_pvb_deaths <- c(d_p_lb,
                      d_p_fd,
                      d_p_lb,
                      d_p_fd,
                      d_p_lb,
                      d_p_lb,
                      d_p_lb,
                      d_p_fd,
                      d_p_lb,
                      d_p_fd,
                      d_p_lb,
                      d_p_lb,
                      d_p_lb,
                      d_p_lb,
                      d_p_lb,
                      d_p_lb)
    
                
    # vector of transfusions
    v_transfusion <- c(n_it,
                       n_it,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_it,
                       n_it,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt,
                       n_nt)
    
      # total costs per policy
      total_cost_sq  <- v_w_sq  %*%  v_cost_sq    
      total_cost_surv <- v_w_surv    %*%  v_cost_surv
      # total deaths per policy
      total_death_sq <- v_w_sq %*% v_death %*% pop_size
      total_death_surv <- v_w_surv %*% v_death %*% pop_size
      total_pvb_deaths_sq <- v_w_sq %*% v_pvb_deaths %*% pop_size
      total_pvb_deaths_surv <- v_w_surv %*% v_pvb_deaths %*% pop_size
      # total transfusions per policy
      total_it_sq <- v_w_sq %*% v_transfusion %*% pop_size
      total_it_surv <- v_w_surv %*% v_transfusion %*% pop_size
      
      # name outcomes
      #names(total_cost_sq) <- v_names_str
      #names(total_cost_surv) <- v_names_str
      #names(total_death_sq) <- v_names_str
      #names(total_death_surv) <- v_names_str
      #names(total_it_sq) <- v_names_str
      #names(total_it_surv) <- v_names_str
      
      
      print(sum(v_w_sq))
      print(sum(v_w_surv))
      
      df_output <- data.frame(Strategy =  v_names_str,
                              Cost     =  total_cost_surv - total_cost_sq,
                              Total_Deaths  =  total_death_surv,
                              B19_Deaths_SQ = total_pvb_deaths_sq,
                              B19_Deaths_Surv = total_pvb_deaths_surv,
                              Deaths_Averted = total_death_sq - total_death_surv, 
                              IUTs_SQ = total_it_sq,
                              IUTs_Surv = total_it_surv)
     return(df_output)})
}

```

```{r, warning = FALSE}
# one way sensitivity analysis
# Cost is total cost of each policy
# Deaths is total number of deaths, B19 related and otherwise
# B19SQ is # of B19 related deaths in status quo
# B19Surv is the # of B19 related deaths in surveillance
# Averted is the difference in number of # B19 related deaths from status quo to surveillance
# ITSQ is the # of transfusions performed in status quo
# ITSurv is the # of transfusions performed in surveillance
base_case <- run_tree(l_params_all)
base_case

```